"""
Feature-to-stratum assignment audit table generator.

Loads the fitted FeatureStratifier from mkb.pkl and emits the complete
per-stratum base-measure-family enumeration as LaTeX (a summary table plus
one longtable per stratum), so the thesis appendix is machine-generated
from the deployed artifact rather than hand-transcribed.

A "base-measure family" is a Lingualyzer base measure with its level-
statistic suffix stripped: e.g. "Word length (Par SD)" and
"Word length (Doc)" both belong to the family "Word length".

Usage::

    python analysis/stratum_audit.py [--mkb mkb.pkl] [--out analysis/stratum_audit_tables.tex]
"""

from __future__ import annotations

import argparse
import collections
import pickle
import re
from pathlib import Path

# Presentation order (S1..S5), distinct from the first-match-wins
# priority order (S4, S5, S1, S2, S3) used during assignment.
_DISPLAY = {
    "S1_morphological":     ("S1", "Morphological Richness"),
    "S2_lexical_diversity": ("S2", "Lexical Diversity"),
    "S3_structural":        ("S3", "Structural/Syntactic"),
    "S4_info_theoretic":    ("S4", "Information-Theoretic"),
    "S5_cross_level":       ("S5", "Cross-Level Cohesion"),
}
_ORDER = ["S1_morphological", "S2_lexical_diversity", "S3_structural",
          "S4_info_theoretic", "S5_cross_level"]

_SUFFIX_RE = re.compile(r"\s*\((Sent|Par|Doc)[^)]*\)\s*$")


def base_family(feature_name: str) -> str:
    return _SUFFIX_RE.sub("", feature_name).strip()


def tex_escape(s: str) -> str:
    for ch, rep in [("&", r"\&"), ("%", r"\%"), ("_", r"\_"), ("#", r"\#")]:
        s = s.replace(ch, rep)
    return s


def fmt_int(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mkb", default="mkb.pkl")
    ap.add_argument("--out", default="analysis/stratum_audit_tables.tex")
    args = ap.parse_args()

    with open(args.mkb, "rb") as fh:
        mkb = pickle.load(fh)
    strat = mkb.stratifier

    lines: list[str] = []
    lines.append("% ── AUTO-GENERATED by analysis/stratum_audit.py — do not edit by hand ──")
    lines.append(f"% Source artifact: {args.mkb}")
    lines.append("")

    # ── Summary table ────────────────────────────────────────────────────
    total_feats = sum(len(f.feature_names) for f in strat._fits.values())
    fams_per = {}
    for key in _ORDER:
        fit = strat._fits[key]
        fams = collections.Counter(base_family(f) for f in fit.feature_names)
        fams_per[key] = fams
    total_fams = sum(len(f) for f in fams_per.values())
    total_pcs = sum(f.n_components for f in strat._fits.values())

    lines.append(r"\begin{table}[H]")
    lines.append(r"    \centering")
    lines.append(r"    \caption{Per-stratum summary of the deterministic feature-to-stratum "
                 r"assignment, extracted from the fitted \texttt{FeatureStratifier} in the "
                 r"deployed Meta-Knowledge Base. Variance is the cumulative proportion "
                 r"explained by the retained principal components.}")
    lines.append(r"    \label{tab:stratum_audit_summary}")
    lines.append(r"    \begin{tabular}{|l|r|r|r|r|}")
    lines.append(r"        \hline")
    lines.append(r"        \textbf{Stratum} & \textbf{Families} & \textbf{Core features} & "
                 r"\textbf{PCs} & \textbf{Variance} \\")
    lines.append(r"        \hline")
    for key in _ORDER:
        fit = strat._fits[key]
        sid, sname = _DISPLAY[key]
        var = sum(fit.explained_variance_ratio) * 100
        lines.append(f"        {sid} --- {sname} & {len(fams_per[key])} & "
                     f"{fmt_int(len(fit.feature_names))} & {fit.n_components} & "
                     f"{var:.1f}\\% \\\\")
        lines.append(r"        \hline")
    lines.append(f"        \\textbf{{Total}} & \\textbf{{{total_fams}}} & "
                 f"\\textbf{{{fmt_int(total_feats)}}} & \\textbf{{{total_pcs}}} & --- \\\\")
    lines.append(r"        \hline")
    lines.append(r"    \end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")

    # ── One longtable per stratum ────────────────────────────────────────
    for key in _ORDER:
        fit = strat._fits[key]
        sid, sname = _DISPLAY[key]
        fams = sorted(fams_per[key].items())
        n_feats = len(fit.feature_names)

        lines.append(r"\begin{small}")
        lines.append(r"\begin{longtable}{|l|r||l|r|}")
        lines.append(f"\\caption{{{sid} --- {sname}: complete base-measure family "
                     f"enumeration ({len(fams)} families, {fmt_int(n_feats)} core "
                     f"features). Var.\\ is the number of level--statistic variants "
                     f"of the family assigned to this stratum.}}")
        lines.append(f"\\label{{tab:stratum_audit_{sid.lower()}}}\\\\")
        header = (r"\hline" "\n"
                  r"\textbf{Base-measure family} & \textbf{Var.} & "
                  r"\textbf{Base-measure family} & \textbf{Var.} \\" "\n"
                  r"\hline")
        lines.append(header)
        lines.append(r"\endfirsthead")
        lines.append(r"\multicolumn{4}{l}{\footnotesize\textit{"
                     f"{sid} --- {sname} (continued)}}}}\\\\".replace("}}}}", "}}"))
        lines.append(header)
        lines.append(r"\endhead")
        lines.append(r"\hline")
        lines.append(r"\endfoot")
        lines.append(r"\hline")
        lines.append(r"\endlastfoot")
        half = (len(fams) + 1) // 2
        for i in range(half):
            left = fams[i]
            right = fams[i + half] if i + half < len(fams) else None
            lcell = f"{tex_escape(left[0])} & {left[1]}"
            rcell = f"{tex_escape(right[0])} & {right[1]}" if right else " & "
            lines.append(f"{lcell} & {rcell} \\\\")
        lines.append(r"\end{longtable}")
        lines.append(r"\end{small}")
        lines.append("")

    out = Path(args.out)
    out.write_text("\n".join(lines), encoding="utf-8")

    # ── Console verification summary ─────────────────────────────────────
    print(f"Written: {out}")
    print(f"Core features: {total_feats}   families: {total_fams}   PCs: {total_pcs}")
    for key in _ORDER:
        sid, sname = _DISPLAY[key]
        print(f"  {sid} {sname:26s} {len(fams_per[key]):3d} families  "
              f"{len(strat._fits[key].feature_names):4d} features  "
              f"{strat._fits[key].n_components:2d} PCs")


if __name__ == "__main__":
    main()
